### ISSUE TITLE
Add NUTS 2013 regions

### ISSUE THREAD

**Issue by patperu** [ropenscilabs/charlatan#44]
see http://ec.europa.eu/eurostat/web/nuts/overview (at least Level II)

**Comment by sckott** [comment]
@patperu to which thing in this pkg? or are you suggesting a new data type?

**Comment by patperu** [comment]
@sckott  I would suggest a new data type - maybe in `statistics-EU-NUTS.R`

**Comment by patperu** [comment]
@sckott let's close this for now. Not sure if it makes sense to generate the regions multiple times
